export const SELECT_CURRENCY = "SELECT_CURRENCY"
export const SELECT_DATE_RANGE = "SELECT_DATE_RANGE"
export const INPUT_QUANTITY = "INPUT_QUANTITY"
export const CALCULATE = "CALCULATE"
export const GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE"
export const DEFAULT_RATE_FOR_TODAY = "DEFAULT_RATE_FOR_TODAY"
export const GET_ALL_CURRENCIES = "GET_ALL_CURRENCIES"


// sufixes
export const START = "START"
export const SUCCESS = "SUCCESS"
export const FAILED = "FAILED"

