export const SELECT_CURRENCY = "SELECT_CURRENCY"
export const SELECT_DATE_RANGE = "SELECT_DATE_RANGE"
export const INPUT_QUANTITY = "INPUT_QUANTITY"
export const CALCULATE = "CALCULATE"
export const GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE"
export const DEFAULT_RATE_FOR_TODAY = "DEFAULT_RATE_FOR_TODAY"
export const GET_ALL_CURRENCIES = "GET_ALL_CURRENCIES"
export const INCREMENT = "INCREMENT"


// sufixes
export const START = "_START"
export const SUCCESS = "_SUCCESS"
export const FAILED = "_FAILED"

